# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "github.com/tektoncd/plumbing/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
]

[[constraint]]
  name = "github.com/tektoncd/pipeline"
  # Pipeline trun to knative.dev
  revision = "42bc3fbd5fc3ed35bfad1f371ef585da92b5fdc6"

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "knative.dev/caching"
  # HEAD as of 2019-07-23
  revision = "2032732871ff807958e045858b462d372eec9587"

[[constraint]]
  name = "github.com/tektoncd/plumbing"
  # HEAD as of 2019-07-23
  revision = "a268939d0be5ed810f541269f9dd606bb2e66090"

[[constraint]]
  name = "github.com/knative/test-infra"
  # HEAD as of 2019-06-25
  revision = "69af8af1d3fec861ada88efc72409b3467b0588d"

[[override]]
  name = "knative.dev/pkg"
  # HEAD as of 2019-07-23 ðŸ’–
  revision = "e4bc08cc8deda3eac40a8d53984d09c9d0e1ad48"

[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[[override]]
  name = "contrib.go.opencensus.io/exporter/prometheus"
  version = "0.1.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.12.2"

[[override]]
  name = "google.golang.org/genproto"
  # Lock the version of proto package to v2 to keep things building.
  revision = "fc2db5cae922db113989ef87b5b859cc8a179f59"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  # Lock the version of proto package to v2 to keep things building.
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/tektoncd/plumbing"
  non-go = false

 [[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false
